apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- infrastructure
- applications

patchesStrategicMerge:
- overlays/patchToolingStack.yaml
- overlays/patchMonitoringStack.yaml

patches:
  - target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    path: overlays/patchFluxKustomizeController.yaml

  - target:
      kind: GitRepository
      name: flux-system
      namespace: flux-system
    path: overlays/patchFluxRepository.yaml
