# Configuration patches for Monitoring Stack

---
# Patch the deployment to use the 'production' manifests and overlays
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  # As a default deployment environment, SRE members set 'develop',
  # but 'production' is more desirable for reliability purposes.
  path: ./flux/production

---
# Patch the git repository reference to fix the tag
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  ref:
    tag: v0.1.0
